---
title: "Titulo do artigo"
author: "Orlando Carlos Huertas Tavares"
data: "20 02 2019"
---

```{r,  eval=FALSE}
rmarkdown::render("main.Rmd", encoding = "UTF-8", output_dir = "../docs/")
```

```{r}
library(magrittr)
```

#control + alt + i

```{r}
2+2

```

#pipe =ctr + shifit + M
# %<>% # analisa a coluna e troca essa pelo resultado ex: exemplo transforma os dados e substitue as originais
# %$%  # seleciona as colunas por exemplo para analise de correlação entre 2 colunas somente
```{r}
z <-log (25) %>% sqrt() %>%  log() %T>% print()
```

```{r}
lm() 
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
lm.D90 <- lm(weight ~ group - 1) # omitting intercept

anova(lm.D9)
summary(lm.D90)

opar <- par(mfrow = c(2,2), oma = c(0, 0, 1.1, 0))
plot(lm.D9, las = 1)      # Residuals, Fitted, ...
par(opar)

lm(weight ~ group) %T>% plot() %>% anova() #mostra todos os graficos

ou

lm(weight ~ group) %T>% plot(which=1) %>% anova() #which=1 para mostrar 1 grafico por vez
```

